const root=panel.root,zh=panel.lang==="zh";
const L=zh?{
 title:"仓库管理",subtitle:"配置容量，并查看或编辑个人与小队仓库。",settings:"容量设置",teams:"小队仓库",contents:"仓库查看",save:"保存设置",
 teamsTitle:"小队仓库",teamsHelp:"点击小队即可在仓库查看中打开；恢复隔离区合并显示在本页下方。",teamEmpty:"尚未创建小队仓库。",purchased:"已购买",version:"版本",status:"状态",pending:"待恢复",overCapacity:"占用超过容量",
 recoveryTitle:"恢复隔离区",recoveryHelp:"容量购买只能经明确确认并写入审计后解决；状态不确定的物品存取不会自动重放。",purchaseRecoveryTitle:"待恢复容量购买",transferRecoveryTitle:"中断的物品存取",resolutionAuditTitle:"购买解决审计",nonePending:"没有待恢复记录。",abortUnpaid:"安全中止",retryRefund:"重试退款",confirmRefunded:"确认已退款",resolutionNote:"请输入解决原因（写入审计）",typeOperation:"输入完整操作号以确认：",resolutionDone:"解决操作已完成。",
 contentsTitle:"仓库查看",contentsHelp:"从玩家或小队列表快捷选择，也可手工输入所有者 ID；当前仓库容量和物品记录均可编辑。",ownersTitle:"有库存的玩家",ownersHelp:"点击玩家即可打开个人仓库。",inspectionTeamsTitle:"小队仓库",inspectionTeamsHelp:"点击小队即可打开共享仓库。",ownersSearch:"筛选",unknownGame:"未知游戏昵称",unknownSteam:"未知 Steam 昵称",
 kind:"仓库类型",personal:"个人",team:"小队",ownerKey:"所有者 ID",load:"加载",addItem:"＋ 添加物品",capacity:"当前容量",updateCapacity:"更新容量",used:"已用",bulk:"要批量删除的物品 ID",bulkDelete:"删除全部匹配项",
 edit:"编辑",remove:"删除",editTitle:"编辑仓库记录",addTitle:"添加物品",itemId:"物品 ID",amount:"物品内部数量",quality:"品质 (0–100)",copies:"添加份数",record:"记录",cells:"格",saveItem:"保存修改",confirmAdd:"确认添加",cancel:"取消",
 buyer:"买家",owner:"仓库",operation:"操作号",created:"创建",updated:"更新",direction:"方向",actor:"操作者",payload:"完整物品载荷",economy:"经济模式",
 invalidOwner:"请选择有效仓库。个人仓库需要 17 位 SteamID，小队仓库需要稳定小队 ID。",invalidItem:"请输入有效物品 ID。",loadFirst:"请先加载当前输入的仓库。",requestFailed:"请求失败。",empty:"当前仓库为空。",capacityInvalid:"容量必须为正整数，且不能小于当前占用。",
 deleteConfirm:"确定删除记录 #{record}（物品 #{item}）？此操作不可撤销。",bulkConfirm:"确定删除当前仓库内所有 ID 为 {id} 的物品？此操作不可撤销。"
}:{
 title:"Vault management",subtitle:"Configure capacity and inspect or edit personal and team vaults.",settings:"Capacity",teams:"Team vaults",contents:"Vault inspection",save:"Save settings",
 teamsTitle:"Team vaults",teamsHelp:"Open a team in Vault inspection; recovery quarantine is included below.",teamEmpty:"No team vault has been created.",purchased:"purchased",version:"version",status:"status",pending:"pending",overCapacity:"usage exceeds capacity",
 recoveryTitle:"Recovery quarantine",recoveryHelp:"Capacity purchases require an explicitly confirmed, audited resolution. Uncertain transfers are never replayed automatically.",purchaseRecoveryTitle:"Pending capacity purchases",transferRecoveryTitle:"Interrupted inventory transfers",resolutionAuditTitle:"Purchase resolution audit",nonePending:"No pending recovery records.",abortUnpaid:"Cancel safely",retryRefund:"Retry refund",confirmRefunded:"Confirm refunded",resolutionNote:"Enter the resolution reason (written to audit)",typeOperation:"Type the full operation ID to confirm:",resolutionDone:"Resolution completed.",
 contentsTitle:"Vault inspection",contentsHelp:"Pick a player or team, or enter an owner ID manually. Capacity and exact stored rows can be edited.",ownersTitle:"Players with stored items",ownersHelp:"Click a player to open the personal vault.",inspectionTeamsTitle:"Team vaults",inspectionTeamsHelp:"Click a team to open the shared vault.",ownersSearch:"Filter",unknownGame:"Unknown game name",unknownSteam:"Unknown Steam name",
 kind:"Vault type",personal:"Personal",team:"Team",ownerKey:"Owner ID",load:"Load",addItem:"＋ Add item",capacity:"Current capacity",updateCapacity:"Update capacity",used:"used",bulk:"Item ID to delete",bulkDelete:"Delete all matching",
 edit:"Edit",remove:"Delete",editTitle:"Edit stored row",addTitle:"Add item",itemId:"Item ID",amount:"Internal amount",quality:"Quality (0–100)",copies:"Copies",record:"Record",cells:"cells",saveItem:"Save changes",confirmAdd:"Add items",cancel:"Cancel",
 buyer:"buyer",owner:"vault",operation:"operation",created:"created",updated:"updated",direction:"direction",actor:"actor",payload:"exact item payload",economy:"economy mode",
 invalidOwner:"Choose a valid vault. Personal vaults require a 17-digit Steam ID; team vaults require a stable team ID.",invalidItem:"Enter a valid item ID.",loadFirst:"Load the currently entered vault first.",requestFailed:"Request failed.",empty:"This vault is empty.",capacityInvalid:"Capacity must be a positive integer and cannot be lower than current usage.",
 deleteConfirm:"Delete record #{record} (item #{item})? This cannot be undone.",bulkConfirm:"Delete every item with ID {id} from this vault? This cannot be undone."
};
const $=selector=>root.querySelector(selector),make=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!=null)node.textContent=text;return node};
const bodyOf=values=>{const body=new URLSearchParams();for(const [key,value] of Object.entries(values))body.set(key,String(value??""));return body};
const state={ownerKind:"player",ownerKey:"",rows:[],owners:[],teams:[],purchases:[],resolutions:[],transfers:[],capacity:0,used:0,summary:"",generation:0,listGeneration:0};
const tabKey="well404.vault.admin.tab",ownerKeyStorage="well404.vault.admin.owner",kindKey="well404.vault.admin.kind";
$("#title").textContent=L.title;$("#subtitle").textContent=L.subtitle;$("#teams-title").textContent=L.teamsTitle;$("#teams-help").textContent=L.teamsHelp;$("#recovery-title").textContent=L.recoveryTitle;$("#recovery-help").textContent=L.recoveryHelp;$("#purchase-recovery-title").textContent=L.purchaseRecoveryTitle;$("#transfer-recovery-title").textContent=L.transferRecoveryTitle;$("#resolution-audit-title").textContent=L.resolutionAuditTitle;$("#contents-title").textContent=L.contentsTitle;$("#contents-help").textContent=L.contentsHelp;$("#owners-title").textContent=L.ownersTitle;$("#owners-help").textContent=L.ownersHelp;$("#inspection-teams-title").textContent=L.inspectionTeamsTitle;$("#inspection-teams-help").textContent=L.inspectionTeamsHelp;$("#owners-search-label").textContent=L.ownersSearch;$("#kind-label").textContent=L.kind;$("#owner-key-label").textContent=L.ownerKey;$("#load-contents").textContent=L.load;$("#add-item").textContent=L.addItem;$("#capacity-label").textContent=L.capacity;$("#save-capacity").textContent=L.updateCapacity;$("#bulk-label").textContent=L.bulk;$("#bulk-delete").textContent=L.bulkDelete;
const kindSelect=$("#owner-kind");kindSelect.options[0].text=L.personal;kindSelect.options[1].text=L.team;
for(const button of root.querySelectorAll("[data-tab]"))button.textContent=L[button.dataset.tab];
const settingsEntries=[panel.mountAction("settings",$("#settings"))],save=$("#save");save.textContent=L.save;save.onclick=()=>panel.saveSettings(settingsEntries,save);
function selectTab(id){for(const button of root.querySelectorAll("[data-tab]")){const active=button.dataset.tab===id;button.classList.toggle("active",active);button.setAttribute("aria-selected",active?"true":"false")}for(const section of root.querySelectorAll("[data-panel]"))section.classList.toggle("active",section.dataset.panel===id);save.hidden=id!=="settings";try{sessionStorage.setItem(tabKey,id)}catch{}}
let initialTab="settings";try{const saved=sessionStorage.getItem(tabKey);if(["settings","teams","contents"].includes(saved))initialTab=saved;kindSelect.value=sessionStorage.getItem(kindKey)||"player";$("#owner-key").value=sessionStorage.getItem(ownerKeyStorage)||""}catch{}
for(const button of root.querySelectorAll("[data-tab]"))button.onclick=()=>selectTab(button.dataset.tab);selectTab(initialTab);
function message(text,kind="info"){const node=root.querySelector("#contents-message");node.textContent=text||"";node.className=text?"msg "+kind:"msg"}
function listMessage(text,kind="err"){const node=root.querySelector("#teams-message");node.textContent=text||"";node.className=text?"msg "+kind:"msg"}
function ownerRef(){const kind=kindSelect.value==="team"?"team":"player",key=$("#owner-key").value.trim();if(kind==="player"&&!/^\d{17}$/.test(key))return null;if(kind==="team"&&!key)return null;return{ownerKind:kind,ownerKey:key,steamId:kind==="player"?key:""}}
function choose(kind,key){kindSelect.value=kind;$("#owner-key").value=key;selectTab("contents");loadContents()}
function localizedName(text){const lines=String(text||"").split("\n").filter(Boolean),node=make("div","inventory-title");const primary=!zh&&lines.length>1?lines[lines.length-1]:(lines[0]||"");node.append(make("span","name-primary",primary));if(zh&&lines.length>1)node.append(make("span","name-secondary",lines.slice(1).join(" ")));return node}
function renderOwners(){const list=$("#owner-list"),query=$("#owner-search").value.trim().toLocaleLowerCase();list.replaceChildren();const visible=state.owners.filter(record=>{const value=record.values||{};return !query||[record.key,record.label,value.gameName,value.steamName].some(text=>String(text||"").toLocaleLowerCase().includes(query))});if(!visible.length){list.append(make("div","empty",zh?"没有匹配的玩家":"No matching players"));return}for(const record of visible){const value=record.values||{},button=make("button","owner-card"),names=make("span","owner-names"),meta=make("span","owner-meta");names.append(make("strong","",value.gameName||L.unknownGame),make("small","",value.steamName||L.unknownSteam));meta.append(make("span","pill",value.steamId||record.key),make("span","pill",`${value.rows||0} ${zh?"条":"rows"}`),make("span","pill",`${value.usedSlots||0} ${L.cells}`));button.type="button";button.append(names,meta);button.onclick=()=>choose("player",value.steamId||record.key);list.append(button)}}
function teamCard(record,compact=false){const value=record.values||{},button=make("button",compact?"owner-card":"team-card"),names=make("span","owner-names"),meta=make("span","owner-meta"),used=Number(value.usedSlots||0),capacity=Number(value.capacity||0),pending=Number(value.pendingPurchases||0);if(used>capacity)button.classList.add("warning");names.append(make("strong","",value.name||record.label||record.key),make("small","",value.ownerKey||record.key));meta.append(make("span","pill",`${used} / ${capacity} ${L.cells}`),make("span","pill",`${L.purchased}: ${value.purchasedSlots||0}`),make("span","pill",`${L.version}: ${value.version||0}`),make("span",`pill${pending?" warning-pill":""}`,`${L.pending}: ${pending}`));button.type="button";button.append(names,meta);button.onclick=()=>choose("team",value.ownerKey||record.key);return button}
function renderTeams(){const main=$("#team-list"),picker=$("#inspection-team-list");main.replaceChildren();picker.replaceChildren();if(!state.teams.length){main.append(make("div","empty",L.teamEmpty));picker.append(make("div","empty",L.teamEmpty));return}for(const team of state.teams){main.append(teamCard(team));picker.append(teamCard(team,true))}}
async function resolvePurchase(value,action){const operationId=value.operationId||"",note=prompt(L.resolutionNote);if(note==null||note.trim().length<3)return;const confirmation=prompt(`${L.typeOperation}\n${operationId}`);if(confirmation!==operationId)return;try{const result=await panel.invoke("resolvepurchase",bodyOf({operationId,resolution:action,note:note.trim(),confirmation}));if(!result.success)throw new Error(result.message||L.requestFailed);await loadLists();listMessage(result.message||L.resolutionDone,"ok")}catch(error){listMessage(error.message||L.requestFailed,"err")}}
function recoveryCard(record,type){const value=record.values||{},card=make("article","recovery-card"),meta=make("div","owner-meta");if(type==="purchase")meta.append(make("span","pill",`${L.buyer}: ${value.buyerSteamId||"-"}`),make("span","pill",`${L.owner}: ${value.ownerKind||"team"}:${value.ownerKey||value.teamKey||"-"}`),make("span","pill",`${value.slots||0} ${L.cells}`),make("span","pill",String(value.price||0)),make("span","pill",`${L.economy}: ${value.economyMode||"durable"}`),make("span","pill warning-pill",value.state||"pending"));else meta.append(make("span","pill",`${L.actor}: ${value.actorSteamId||"-"}`),make("span","pill",`${L.direction}: ${value.direction||"-"}`),make("span","pill",`${value.ownerKind||"-"}:${value.ownerKey||"-"}`),make("span","pill warning-pill",value.state||"-"));card.append(make("strong","",value.operationId||record.key),meta,make("small","",`${L.created}: ${value.createdUtc||"-"} · ${L.updated}: ${value.updatedUtc||"-"}`));if(type==="transfer")card.append(make("pre","payload",value.items||L.nonePending));if(type==="purchase"){const actions=make("div","recovery-actions");if(["pending","debiting"].includes(value.state)){const abort=make("button","danger",L.abortUnpaid);abort.type="button";abort.onclick=()=>resolvePurchase(value,"abort-unpaid");actions.append(abort)}if(value.state==="refund_pending"){const retry=make("button","",L.retryRefund),confirmButton=make("button","danger",L.confirmRefunded);retry.type=confirmButton.type="button";retry.onclick=()=>resolvePurchase(value,"retry-refund");confirmButton.onclick=()=>resolvePurchase(value,"confirm-refunded");actions.append(retry,confirmButton)}else if(value.state==="debiting"&&value.economyMode==="experience"){const confirmButton=make("button","danger",L.confirmRefunded);confirmButton.type="button";confirmButton.onclick=()=>resolvePurchase(value,"confirm-refunded");actions.append(confirmButton)}card.append(actions)}return card}
function auditCard(record){const value=record.values||{},card=make("article","recovery-card"),meta=make("div","owner-meta");meta.append(make("span","pill",value.action||"-"),make("span","pill",`${value.fromState||"-"} → ${value.toState||"-"}`),make("span","pill",`${L.actor}: ${value.actor||"-"}`));card.append(make("strong","",value.operationId||record.label||"-"),meta,make("small","",value.note||""),make("small","",value.createdUtc||"-"));return card}
function renderRecovery(){const purchases=$("#pending-purchase-list"),transfers=$("#interrupted-transfer-list"),audits=$("#purchase-resolution-list");purchases.replaceChildren();transfers.replaceChildren();audits.replaceChildren();if(!state.purchases.length)purchases.append(make("div","empty",L.nonePending));else for(const item of state.purchases)purchases.append(recoveryCard(item,"purchase"));if(!state.transfers.length)transfers.append(make("div","empty",L.nonePending));else for(const item of state.transfers)transfers.append(recoveryCard(item,"transfer"));if(!state.resolutions.length)audits.append(make("div","empty",L.nonePending));else for(const item of state.resolutions)audits.append(auditCard(item))}
async function loadLists(){const generation=++state.listGeneration;try{const [owners,teams,purchases,resolutions,transfers]=await Promise.all([panel.records("owners"),panel.records("teams"),panel.records("pendingpurchases"),panel.records("purchaseresolutions"),panel.records("interruptedtransfers")]);if(generation!==state.listGeneration)return;state.owners=owners.records||[];state.teams=teams.records||[];state.purchases=purchases.records||[];state.resolutions=resolutions.records||[];state.transfers=transfers.records||[];renderOwners();renderTeams();renderRecovery();listMessage("")}catch(error){if(generation===state.listGeneration){const text=error.message||L.requestFailed;listMessage(text,"err");message(text,"err")}}}
function rowModel(row){return{recordId:row[0],itemId:row[1],name:row[2],amount:row[3],quality:row[4],cells:row[5],maxAmount:row[6]}}
function updateCapacityUi(){$("#capacity").value=state.capacity||"";$("#capacity-used").textContent=state.capacity?`${L.used}: ${state.used} / ${state.capacity} ${L.cells}`:""}
async function loadContents(){const ref=ownerRef();if(!ref){message(L.invalidOwner,"err");return}const generation=++state.generation,button=root.querySelector("#load-contents");button.disabled=true;message(zh?"正在加载…":"Loading…");try{const body=bodyOf(ref),results=await Promise.all([panel.invoke("inventory",body),panel.invoke("containerinfo",body)]),result=results[0],info=results[1];if(generation!==state.generation)return;if(!result.success||!info.success)throw new Error(result.message||info.message||L.requestFailed);state.ownerKind=ref.ownerKind;state.ownerKey=ref.ownerKey;state.rows=result.rows||[];state.summary=result.message||"";const infoRow=(info.rows||[])[0]||[];state.capacity=Number(infoRow[2]||0);state.used=Number(infoRow[3]||0);try{sessionStorage.setItem(kindKey,ref.ownerKind);sessionStorage.setItem(ownerKeyStorage,ref.ownerKey)}catch{}renderContents();updateCapacityUi();message("")}catch(error){if(generation===state.generation)message(error.message||L.requestFailed,"err")}finally{if(generation===state.generation)button.disabled=false}}
function renderContents(){$("#contents-summary").textContent=state.summary;const grid=$("#inventory-grid");grid.replaceChildren();if(!state.rows.length){grid.append(make("div","empty",L.empty));return}for(const raw of state.rows){const item=rowModel(raw),card=make("article","inventory-card"),meta=make("div","inventory-meta"),actions=make("div","inventory-actions");card.append(localizedName(item.name));meta.append(make("span","pill",`#${item.itemId}`),make("span","pill",`×${item.amount}`),make("span","pill",`${L.quality}: ${item.quality}`),make("span","pill",`${item.cells} ${L.cells}`),make("span","pill",`${L.record} ${item.recordId}`));const edit=make("button","ghost",L.edit),remove=make("button","danger",L.remove);edit.type=remove.type="button";edit.onclick=()=>openEditor(item);remove.onclick=()=>deleteOne(item);actions.append(edit,remove);card.append(meta,actions);grid.append(card)}}
function field(form,label,name,value,min,max){const wrap=make("label","field"),input=document.createElement("input");input.type="number";input.name=name;input.value=value;input.min=min;input.max=max;input.step="1";wrap.append(make("span","",label),input);form.append(wrap);return input}
function openModal(title,build){const host=$("#modal-root"),overlay=make("div","modal-overlay"),modal=make("div","modal"),head=make("div","modal-head"),close=make("button","modal-close","×"),dismiss=()=>host.replaceChildren();modal.setAttribute("role","dialog");modal.setAttribute("aria-modal","true");close.type="button";close.onclick=dismiss;head.append(make("h3","",title),close);modal.append(head);build(modal,dismiss);overlay.append(modal);host.replaceChildren(overlay);let pressedOutside=false;overlay.addEventListener("pointerdown",event=>{pressedOutside=event.target===overlay});overlay.addEventListener("pointerup",event=>{const closeNow=pressedOutside&&event.target===overlay;pressedOutside=false;if(closeNow)dismiss()});overlay.addEventListener("pointercancel",()=>{pressedOutside=false})}
function currentBody(extra={}){return bodyOf({ownerKind:state.ownerKind,ownerKey:state.ownerKey,steamId:state.ownerKind==="player"?state.ownerKey:"",...extra})}
function openAddEditor(){const ref=ownerRef();if(!ref){message(L.invalidOwner,"err");return}if(ref.ownerKind!==state.ownerKind||ref.ownerKey!==state.ownerKey){message(L.loadFirst,"err");return}openModal(L.addTitle,(modal,dismiss)=>{const form=make("div","form-grid"),itemId=field(form,L.itemId,"itemId","","1","65535"),amount=field(form,L.amount,"amount","1","1","255"),quality=field(form,L.quality,"quality","100","0","100"),copies=field(form,L.copies,"count","1","1","1000"),status=make("div","msg"),actions=make("div","modal-actions"),cancel=make("button","ghost",L.cancel),submit=make("button","success",L.confirmAdd);cancel.onclick=dismiss;submit.onclick=async()=>{submit.disabled=true;try{const result=await panel.invoke("additem",currentBody({itemId:itemId.value,amount:amount.value,quality:quality.value,count:copies.value}));if(!result.success)throw new Error(result.message||L.requestFailed);dismiss();await loadContents();await loadLists();message(result.message||"","ok")}catch(error){status.textContent=error.message||L.requestFailed;status.className="msg err";submit.disabled=false}};actions.append(cancel,submit);modal.append(form,status,actions);itemId.focus()})}
function openEditor(item){openModal(`${L.editTitle} #${item.recordId}`,(modal,dismiss)=>{const form=make("div","form-grid"),itemId=field(form,L.itemId,"itemId",item.itemId,"1","65535"),amount=field(form,L.amount,"amount",item.amount,"1","255"),quality=field(form,L.quality,"quality",item.quality,"0","100"),status=make("div","msg"),actions=make("div","modal-actions"),cancel=make("button","ghost",L.cancel),submit=make("button","",L.saveItem);cancel.onclick=dismiss;submit.onclick=async()=>{submit.disabled=true;try{const result=await panel.invoke("updateitem",currentBody({recordId:item.recordId,itemId:itemId.value,amount:amount.value,quality:quality.value}));if(!result.success)throw new Error(result.message||L.requestFailed);dismiss();await loadContents();await loadLists();message(result.message||"","ok")}catch(error){status.textContent=error.message||L.requestFailed;status.className="msg err";submit.disabled=false}};actions.append(cancel,submit);modal.append(form,status,actions)})}
async function deleteOne(item){if(!confirm(L.deleteConfirm.replace("{record}",item.recordId).replace("{item}",item.itemId)))return;try{const result=await panel.invoke("deleteitem",currentBody({recordId:item.recordId}));if(!result.success)throw new Error(result.message||L.requestFailed);await loadContents();await loadLists();message(result.message||"","ok")}catch(error){message(error.message||L.requestFailed,"err")}}
async function deleteMatching(){const ref=ownerRef();if(!ref||ref.ownerKind!==state.ownerKind||ref.ownerKey!==state.ownerKey){message(L.loadFirst,"err");return}const itemId=$("#bulk-item-id").value.trim();if(!/^\d+$/.test(itemId)||Number(itemId)<1||Number(itemId)>65535){message(L.invalidItem,"err");return}if(!confirm(L.bulkConfirm.replace("{id}",itemId)))return;const button=$("#bulk-delete");button.disabled=true;try{const result=await panel.invoke("deleteitems",currentBody({itemId}));if(!result.success)throw new Error(result.message||L.requestFailed);await loadContents();await loadLists();message(result.message||"","ok")}catch(error){message(error.message||L.requestFailed,"err")}finally{button.disabled=false}}
async function saveCapacity(){const ref=ownerRef(),capacity=Number($("#capacity").value);if(!ref||ref.ownerKind!==state.ownerKind||ref.ownerKey!==state.ownerKey||!Number.isInteger(capacity)||capacity<1||capacity>1000000||capacity<state.used){message(L.capacityInvalid,"err");return}const button=$("#save-capacity");button.disabled=true;try{const result=await panel.invoke("setcapacity",currentBody({capacity}));if(!result.success)throw new Error(result.message||L.requestFailed);await loadContents();await loadLists();message(result.message||"","ok")}catch(error){message(error.message||L.requestFailed,"err")}finally{button.disabled=false}}
$("#load-contents").onclick=loadContents;$("#add-item").onclick=openAddEditor;$("#bulk-delete").onclick=deleteMatching;$("#save-capacity").onclick=saveCapacity;$("#owner-search").addEventListener("input",renderOwners);$("#owner-key").addEventListener("keydown",event=>{if(event.key==="Enter")loadContents()});kindSelect.onchange=()=>{$("#owner-key").value="";state.ownerKey="";state.rows=[];state.capacity=0;state.used=0;renderContents();updateCapacityUi()};
loadLists();panel.onRefresh(async()=>{if($("#modal-root").children.length)return;await loadLists();if(state.ownerKey)await loadContents()});
