const root=panel.root,zh=panel.lang==="zh";
const labels=zh
  ?{title:"实用工具",subtitle:"管理传送、队伍、礼包与世界时间规则。",teleport:"传送设置",rules:"其他规则",warps:"传送点",gifts:"礼包",search:"检索游戏物品",save:"保存设置",warpsTitle:"传送点目录",warpsHelp:"每个传送点可有多个标签；标签仅用于过滤，卡片顺序全局一致，拖动当前筛选结果即可调整相对顺序。",addWarp:"＋ 新增传送点",all:"全部",edit:"编辑",remove:"删除",cancel:"取消",saveWarp:"保存传送点",name:"名称",tags:"标签（空格分隔）",x:"X",y:"Y",z:"Z",yaw:"朝向",confirmDelete:"确定删除传送点 {name}？",empty:"当前标签下没有传送点。",requestFailed:"请求失败。"}
  :{title:"Essentials",subtitle:"Manage teleport, party, gifts and world-time rules.",teleport:"Teleport",rules:"Rules",warps:"Warps",gifts:"Gifts",search:"Item search",save:"Save settings",warpsTitle:"Warp directory",warpsHelp:"Each warp can have multiple tags. Tags filter one global ordered catalog; drag the visible cards to change their relative order.",addWarp:"＋ Add warp",all:"All",edit:"Edit",remove:"Delete",cancel:"Cancel",saveWarp:"Save warp",name:"Name",tags:"Tags (space-separated)",x:"X",y:"Y",z:"Z",yaw:"Yaw",confirmDelete:"Delete warp {name}?",empty:"No warps under this label.",requestFailed:"Request failed."};
panel.root.querySelector("#title").textContent=labels.title;
panel.root.querySelector("#subtitle").textContent=labels.subtitle;
panel.root.querySelector("#warps-title").textContent=labels.warpsTitle;
panel.root.querySelector("#warps-help").textContent=labels.warpsHelp;
panel.root.querySelector("#add-warp").textContent=labels.addWarp;
for(const button of panel.root.querySelectorAll("[data-tab]"))button.textContent=labels[button.dataset.tab];
const entries=[
  panel.mountAction("teleport",panel.root.querySelector("#teleport")),
  panel.mountAction("rules",panel.root.querySelector("#rules"))
];
panel.mountAction("gifts",panel.root.querySelector("#gifts"));
panel.mountAction("search",panel.root.querySelector("#search"));
const save=panel.root.querySelector("#save");
save.textContent=labels.save;
save.onclick=()=>panel.saveSettings(entries,save);
let active="teleport";
function select(id){
  active=id;
  for(const button of panel.root.querySelectorAll("[data-tab]")){
    const selected=button.dataset.tab===active;
    button.classList.toggle("active",selected);
    button.setAttribute("aria-selected",selected?"true":"false");
  }
  for(const section of panel.root.querySelectorAll("[data-panel]"))section.classList.toggle("active",section.dataset.panel===active);
  save.hidden=active!=="teleport"&&active!=="rules";
}
for(const button of panel.root.querySelectorAll("[data-tab]"))button.onclick=()=>select(button.dataset.tab);
select(active);

const $=selector=>root.querySelector(selector);
const make=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!=null)node.textContent=text;return node};
const bodyOf=values=>{const body=new URLSearchParams();for(const [key,value] of Object.entries(values))body.set(key,String(value??""));return body};
const modulePath=id=>`api/modules/${panel.encode(panel.module.id)}/${panel.encode(id)}`;
const allWarps="__all__",warpState={records:[],active:allWarps,dragKey:"",loading:false};
const splitTags=value=>[...new Set(String(value||"").split(/[\s,]+/).map(tag=>tag.trim().toLowerCase()).filter(Boolean))];
const tagsOf=record=>{const values=record.values||{},tags=splitTags(values.tags);if(tags.length)return tags;if(record.tags?.length)return splitTags(record.tags.join(" "));if(record.groupKey||record.group)return splitTags(record.groupKey||record.group);return ["default"]};
function warpMessage(text,kind="info"){const node=$("#warps-message");node.textContent=text||"";node.className=text?`msg ${kind}`:"msg"}
async function refreshWarps(){if(warpState.loading||$("#modal-root").children.length)return;warpState.loading=true;try{const result=await panel.records("warps");warpState.records=result.records||[];const groups=[...new Set(warpState.records.flatMap(tagsOf))];if(warpState.active!==allWarps&&!groups.includes(warpState.active))warpState.active=allWarps;renderWarps()}catch(error){warpMessage(error.message||labels.requestFailed,"err")}finally{warpState.loading=false}}
function renderWarps(){const tabs=$("#warp-tabs"),grid=$("#warp-grid"),groups=[...new Set(warpState.records.flatMap(tagsOf))];tabs.replaceChildren();for(const [key,label] of [[allWarps,labels.all],...groups.map(group=>[group,group])]){const amount=key===allWarps?warpState.records.length:warpState.records.filter(record=>tagsOf(record).includes(key)).length,button=make("button",warpState.active===key?"active":"",`${label} · ${amount}`);button.type="button";button.setAttribute("aria-pressed",warpState.active===key?"true":"false");button.onclick=()=>{warpState.active=key;renderWarps()};tabs.append(button)}grid.replaceChildren();const visible=warpState.records.filter(record=>warpState.active===allWarps||tagsOf(record).includes(warpState.active));if(!visible.length){grid.append(make("div","empty",labels.empty));return}for(const record of visible)grid.append(warpCard(record,visible))}
function warpCard(record,visible){const values=record.values||{},card=make("article","item warp-card"),title=make("div","title",record.label||record.key),coords=make("div","lines",`(${values.x||0}, ${values.y||0}, ${values.z||0})`),pills=make("div","pills"),actions=make("div","actions"),edit=make("button","primary",labels.edit),remove=make("button","danger",labels.remove);for(const tag of tagsOf(record))pills.append(make("span","pill",tag));edit.type=remove.type="button";edit.onclick=()=>openWarpModal(record);remove.onclick=()=>deleteWarp(record);actions.append(edit,remove);card.append(title,coords,pills,actions);card.draggable=true;card.addEventListener("dragstart",event=>{warpState.dragKey=record.key;card.classList.add("dragging");event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",record.key)});card.addEventListener("dragend",()=>{warpState.dragKey="";card.classList.remove("dragging")});card.addEventListener("dragover",event=>event.preventDefault());card.addEventListener("drop",event=>{event.preventDefault();reorderWarps(warpState.dragKey||event.dataTransfer.getData("text/plain"),record.key,visible)});return card}
async function reorderWarps(fromKey,toKey,visible){const from=visible.findIndex(item=>item.key===fromKey),to=visible.findIndex(item=>item.key===toKey);if(from<0||to<0||from===to)return;const ordered=visible.slice();ordered.splice(to,0,ordered.splice(from,1)[0]);try{const result=await panel.api(`${modulePath("warps")}/reorder`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:bodyOf({tag:warpState.active,keys:ordered.map(item=>item.key).join("\n")}).toString()});if(!result.success)throw new Error(result.message||labels.requestFailed);await refreshWarps();warpMessage(result.message||"","ok")}catch(error){warpMessage(error.message||labels.requestFailed,"err")}}
function warpField(form,label,name,value,type="number",disabled=false){const wrap=make("label","field"),caption=make("span","",label),input=document.createElement("input");input.type=type;input.name=name;input.value=value??"";input.disabled=disabled;if(type==="number")input.step="any";wrap.append(caption,input);form.append(wrap);return input}
function openWarpModal(record=null){const values=record?.values||{},host=$("#modal-root"),overlay=make("div","modal-overlay"),modal=make("div","modal"),head=make("div","modal-head"),dismiss=()=>host.replaceChildren(),close=make("button","modal-close","×");close.type="button";close.onclick=dismiss;head.append(make("h3","",record?`${labels.edit}: ${record.label}`:labels.addWarp),close);modal.append(head);const form=make("div","form-grid"),name=warpField(form,labels.name,"name",values.name||"","text",!!record),tags=warpField(form,labels.tags,"tags",values.tags||(warpState.active===allWarps?"default":warpState.active),"text"),x=warpField(form,labels.x,"x",values.x||"0"),y=warpField(form,labels.y,"y",values.y||"0"),z=warpField(form,labels.z,"z",values.z||"0"),yaw=warpField(form,labels.yaw,"yaw",values.yaw||"0");modal.append(form);const status=make("div","msg"),actions=make("div","modal-actions"),cancel=make("button","ghost",labels.cancel),submit=make("button","primary",labels.saveWarp);cancel.type=submit.type="button";cancel.onclick=dismiss;submit.onclick=async()=>{submit.disabled=true;try{const result=await panel.invoke("warps",bodyOf({name:name.value,tags:tags.value,x:x.value,y:y.value,z:z.value,yaw:yaw.value,recordKey:record?.key||""}));if(!result.success)throw new Error(result.message||labels.requestFailed);dismiss();const savedTags=splitTags(tags.value);if(warpState.active!==allWarps&&!savedTags.includes(warpState.active))warpState.active=savedTags[0]||"default";await refreshWarps();warpMessage(result.message||"","ok")}catch(error){status.textContent=error.message||labels.requestFailed;status.className="msg err";submit.disabled=false}};actions.append(cancel,submit);modal.append(status,actions);overlay.append(modal);host.replaceChildren(overlay);let pressedOutside=false;overlay.addEventListener("pointerdown",event=>{pressedOutside=event.target===overlay});overlay.addEventListener("pointerup",event=>{const closeNow=pressedOutside&&event.target===overlay;pressedOutside=false;if(closeNow)dismiss()});overlay.addEventListener("pointercancel",()=>{pressedOutside=false});name.focus()}
async function deleteWarp(record){if(!confirm(labels.confirmDelete.replace("{name}",record.label||record.key)))return;try{const result=await panel.api(`${modulePath("warps")}/delete`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:bodyOf({key:record.key}).toString()});if(!result.success)throw new Error(result.message||labels.requestFailed);await refreshWarps();warpMessage(result.message||"","ok")}catch(error){warpMessage(error.message||labels.requestFailed,"err")}}
$("#add-warp").onclick=()=>openWarpModal();refreshWarps();panel.onRefresh(refreshWarps);
